# Generated by Django 5.2.17 on 2026-10-04 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'compétence',
                'verbose_name_plural': 'compétences',
            },
        ),
        migrations.CreateModel(
            name='EnseignantReferent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10, verbose_name='Sexe')),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('matricule', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'enseignant référent',
                'verbose_name_plural': 'enseignants référents',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('ville', models.CharField(max_length=80)),
                ('secteur', models.CharField(choices=[('technologie', 'Technologie'), ('commerce', 'Commerce'), ('sante', 'Sante'), ('finance', 'Finance'), ('industrie', 'Industrie'), ('autre', 'Autre')], default='autre', max_length=80)),
                ('contact', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'entreprise',
                'verbose_name_plural': 'entreprises',
                'ordering': ['nom'],
                'constraints': [models.UniqueConstraint(fields=('nom', 'ville'), name='nom_ville_unique')],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10, verbose_name='Sexe')),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('promotion', models.CharField(max_length=20)),
                ('competences', models.ManyToManyField(related_name='etudiants', to='stages.competence')),
            ],
            options={
                'verbose_name': 'étudiant',
                'verbose_name_plural': 'étudiants',
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_places', models.IntegerField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='stages.entreprise')),
            ],
            options={
                'verbose_name': 'offre',
                'verbose_name_plural': 'offres',
            },
        ),
        migrations.AddField(
            model_name='competence',
            name='offres',
            field=models.ManyToManyField(related_name='competences', to='stages.offre'),
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('accepter', 'Accepter'), ('refuser', 'Refuser'), ('en attente', 'Attente')], default='en attente', max_length=80)),
                ('date_depot', models.DateField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='stages.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='stages.offre')),
            ],
            options={
                'verbose_name': 'candidature',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=120)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage', to='stages.candidature')),
                ('enseignant_referent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.enseignantreferent')),
            ],
            options={
                'verbose_name': 'stage',
                'verbose_name_plural': 'stages',
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='stages',
            field=models.ManyToManyField(related_name='etudiants', to='stages.stage'),
        ),
        migrations.CreateModel(
            name='TuteurEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10, verbose_name='Sexe')),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('matricule', models.CharField(max_length=120)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuteur_entreprises', to='stages.entreprise')),
            ],
            options={
                'verbose_name': 'tuteur_entreprise',
                'verbose_name_plural': 'personnes',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='tuteur_entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.tuteurentreprise'),
        ),
    ]
