# Generated by Django 5.2.17 on 2026-09-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='secteur',
            field=models.CharField(choices=[('technologie', 'Technologie'), ('commerce', 'Commerce'), ('sante', 'Sante'), ('finance', 'Finance'), ('industrie', 'Industrie'), ('autre', 'Autre')], default='autre', max_length=80),
        ),
        migrations.AddConstraint(
            model_name='entreprise',
            constraint=models.UniqueConstraint(fields=('nom', 'ville'), name='nom_ville_unique'),
        ),
    ]
