# Generated by Django 5.2.17 on 2026-10-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuteurentreprise',
            options={'verbose_name': 'tuteur_entreprise', 'verbose_name_plural': 'tuteurs_entreprises'},
        ),
    ]
