# Generated by Django 5.2.17 on 2026-09-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_alter_entreprise_secteur_entreprise_nom_ville_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10, verbose_name='Sexe')),
                ('date_naissance', models.DateField()),
            ],
            options={
                'verbose_name': 'personne',
                'verbose_name_plural': 'personnes',
            },
        ),
    ]
