# Generated by Django 5.2.17 on 2026-10-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_alter_tuteurentreprise_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='offres',
        ),
        migrations.AddField(
            model_name='offre',
            name='competences',
            field=models.ManyToManyField(related_name='offres', to='stages.competence'),
        ),
    ]
